"""
Django settings for PersonalHomePage project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import warnings
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from os import getenv as env
from os import path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Load environment variables from .env file
load_dotenv(path.join(BASE_DIR, '.env'))


def env_bool(name: str, default: bool = False) -> bool:
    """Parse a boolean env var explicitly.

    Avoids the classic `bool(os.getenv(...))` footgun where any non-empty
    string (including "False", "0", "no") evaluates to True.

    Truthy values (case-insensitive): "1", "true", "yes", "on".
    Everything else — including unset — is falsy.
    """
    raw = env(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    """Parse a comma-separated env var into a list of strings.

    Strips whitespace around each item and drops empties, so
    "example.com, www.example.com,, " -> ["example.com", "www.example.com"].
    """
    raw = env(name)
    if raw is None:
        return list(default) if default is not None else []
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', default=False)

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = env('SECRET_KEY')
if not _secret_key:
    if DEBUG:
        # Insecure fallback for local dev ONLY. Never usable in production
        # because production must run with DEBUG=False.
        _secret_key = 'django-insecure-dev-only-key-do-not-use-in-production'
        warnings.warn(
            'SECRET_KEY is not set; using an insecure development key. '
            'Set SECRET_KEY in your .env before deploying.',
            stacklevel=2,
        )
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY environment variable is required when DEBUG=False. '
            'Refusing to start without it.'
        )
SECRET_KEY = _secret_key

# Comma-separated list of host/domain names this site can serve.
# e.g. ALLOWED_HOSTS=example.com,www.example.com
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS')

ADMINS = [(env('ADMIN_NAME', ''), env('ADMIN_EMAIL', ''))]

EMAIL_HOST_USER = env('EMAIL_HOST_USER', '')  # email address that will be used to send emails (should be a gmail account)

EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', '')  # password of the email-id

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_USE_TLS = True

EMAIL_PORT = 587

REGION = 'US'

LISTED_NAME = env('LISTED_NAME', '')  # name that will be listed on the home page

LISTED_TITLE = env('LISTED_TITLE', '')  # title that will be listed on the home page

LISTED_EMAIL = env('LISTED_EMAIL', '')  # email that will be listed on the home page

LISTED_PHONE = env('LISTED_PHONE', '')  # phone number that will be listed on the home page

LISTED_GITHUB = env('LISTED_GITHUB', '')  # github link

LISTED_LINKEDIN = env('LISTED_LINKEDIN', '')  # linkedin link

LISTED_TWITTER = env('LISTED_TWITTER', '')  # twitter link

LISTED_DISCORD = env('LISTED_DISCORD', '')  # discord link

LISTED_IN_TEXT_TITLE = env('IN_TEXT_TITLE', '')  # Title that will appear in text and blurbs

HOMEPAGE_IMAGE_CAPTION = env('HOMEPAGE_IMAGE_CAPTION', '')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "blog.apps.BlogConfig",
    "home.apps.HomeConfig",
    "contactme.apps.ContactmeConfig",
    "phonenumber_field",
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PersonalHomePage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PersonalHomePage.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': env('DATABASE_PATH', default=BASE_DIR / 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise static file serving (Django 4.2+ STORAGES API)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SECURE = True
