"""
Django settings for PersonalHomePage project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from os import getenv as env
from os import path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Load environment variables from .env file
load_dotenv(path.join(BASE_DIR, '.env'))


def env_bool(name: str, default: bool = False) -> bool:
    """Parse a boolean env var explicitly.

    Avoids the classic `bool(os.getenv(...))` footgun where any non-empty
    string (including "False", "0", "no") evaluates to True.

    Truthy values (case-insensitive): "1", "true", "yes", "on".
    Everything else — including unset — is falsy.
    """
    raw = env(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: list[str] | None = None) -> list[str]:
    """Parse a comma-separated env var into a list of strings.

    Strips whitespace around each item and drops empties, so
    "example.com, www.example.com,, " -> ["example.com", "www.example.com"].
    """
    raw = env(name)
    if raw is None:
        return list(default) if default is not None else []
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# Always required. DEBUG=True is not an excuse for a baked-in key that can
# leak into a Railway image if someone flips the wrong env var.
_secret_key = env('SECRET_KEY')
if not _secret_key:
    raise ImproperlyConfigured(
        'SECRET_KEY environment variable is required. '
        'Refusing to start without it.'
    )
SECRET_KEY = _secret_key

# Comma-separated list of host/domain names this site can serve.
# e.g. ALLOWED_HOSTS=example.com,www.example.com
# Empty list fail-closes (Django denies every Host). That is intentional.
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS')
# Railway probes /health/ with this Host. Harmless if unused locally.
if 'healthcheck.railway.app' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('healthcheck.railway.app')

# Railway / any TLS-terminating proxy. Trust X-Forwarded-Proto so secure
# cookies and CSRF work behind https://mslevin.dev.
if env_bool('TRUST_PROXY', default=not DEBUG):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True

# Explicit origins preferred. If unset, derive https:// from ALLOWED_HOSTS
# so a Railway deploy with ALLOWED_HOSTS=mslevin.dev,www.mslevin.dev works.
_csrf_origins = env_list('CSRF_TRUSTED_ORIGINS')
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = _csrf_origins
else:
    CSRF_TRUSTED_ORIGINS = []
    for host in ALLOWED_HOSTS:
        if not host or host in {'localhost', '127.0.0.1', '[::1]', 'healthcheck.railway.app'}:
            continue
        if host.startswith('.'):
            CSRF_TRUSTED_ORIGINS.append(f'https://*{host}')
        elif host.startswith('*.'):
            CSRF_TRUSTED_ORIGINS.append(f'https://{host}')
        else:
            CSRF_TRUSTED_ORIGINS.append(f'https://{host}')
    if DEBUG:
        CSRF_TRUSTED_ORIGINS.extend(
            [
                'http://localhost',
                'http://127.0.0.1',
                'http://localhost:8000',
                'http://127.0.0.1:8000',
            ]
        )

# Django 6.0 deprecates ADMINS as a list of (name, email) tuples; use the
# "Name <email>" string format (or bare email) instead.
_admin_name = env('ADMIN_NAME', '')
_admin_email = env('ADMIN_EMAIL', '')
ADMINS = [f'{_admin_name} <{_admin_email}>' if _admin_name else _admin_email] if _admin_email else []

EMAIL_HOST_USER = env('EMAIL_HOST_USER', '')  # email address that will be used to send emails (should be a gmail account)

EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', '')  # password of the email-id

# Overridable so local dev can use the console backend without SMTP creds.
# e.g. EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
EMAIL_BACKEND = env('EMAIL_BACKEND') or 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_USE_TLS = True

EMAIL_PORT = 587

REGION = 'US'

LISTED_NAME = env('LISTED_NAME', '')  # name that will be listed on the home page

LISTED_TITLE = env('LISTED_TITLE', '')  # title that will be listed on the home page

LISTED_EMAIL = env('LISTED_EMAIL', '')  # email that will be listed on the home page

LISTED_PHONE = env('LISTED_PHONE', '')  # phone number that will be listed on the home page

LISTED_GITHUB = env('LISTED_GITHUB', '')  # github link

LISTED_LINKEDIN = env('LISTED_LINKEDIN', '')  # linkedin link

LISTED_TWITTER = env('LISTED_TWITTER', '')  # twitter link

LISTED_DISCORD = env('LISTED_DISCORD', '')  # discord link

LISTED_IN_TEXT_TITLE = env('IN_TEXT_TITLE', '')  # Title that will appear in text and blurbs

HOMEPAGE_IMAGE_CAPTION = env('HOMEPAGE_IMAGE_CAPTION', '')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "blog.apps.BlogConfig",
    "home.apps.HomeConfig",
    "contactme.apps.ContactmeConfig",
    "phonenumber_field",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PersonalHomePage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PersonalHomePage.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': env('DATABASE_PATH') or (BASE_DIR / 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# No user media in v1 (LOG.md 2026-08-20): every image on the site is a
# static asset served by WhiteNoise. There is intentionally no MEDIA_URL,
# MEDIA_ROOT, or upload model, so nothing can 404 behind a DEBUG-only
# static() helper in production.

# WhiteNoise static file serving (Django 4.2+ STORAGES API)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Secure cookies in production. Local DEBUG keeps them off so http://localhost works.
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SECURE_REDIRECT_EXEMPT = [r'^health/$', r'^healthcheck/$']
SERVER_EMAIL = env('SERVER_EMAIL') or env('ADMIN_EMAIL') or 'webmaster@localhost'
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL') or EMAIL_HOST_USER or SERVER_EMAIL
if not DEBUG:
    SECURE_HSTS_SECONDS = int(env('SECURE_HSTS_SECONDS') or '31536000')
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', default=False)

# manage.py test / pytest should not require a collected manifest or HTTPS.
TESTING = env_bool('DJANGO_TEST', default=False) or any(
    arg in sys.argv for arg in ('test', 'pytest')
)
if TESTING:
    STORAGES['staticfiles'] = {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    }
    SECURE_SSL_REDIRECT = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ['testserver', 'localhost', '127.0.0.1']
