# Generated by Django 6.0.8 on 2026-08-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
