# Generated by Django 6.0.8 on 2026-08-20 14:29

from django.db import migrations, models


def approve_existing_comments(apps, schema_editor):
    # Comments that predate moderation were already publicly visible on the
    # old production site; hiding them retroactively would be a silent
    # content change. New comments default to unapproved.
    Comment = apps.get_model('blog', 'Comment')
    Comment.objects.update(approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            approve_existing_comments, migrations.RunPython.noop
        ),
    ]
