# Generated by Django 6.0.8 on 2026-08-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
