# Generated by Django 5.1.2 on 2024-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('proficiency', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=15)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current', models.BooleanField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=15)),
                ('link', models.URLField()),
                ('skills', models.ManyToManyField(to='home.skill')),
            ],
        ),
    ]
