# Generated by Django 5.1.2 on 2024-11-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_skill_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='link',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='link',
            new_name='url',
        ),
    ]
