# Generated by Django 5.1.3 on 2024-11-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_link_experience_url_rename_link_skill_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='importance_value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(blank=True, to='home.skill'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
